import { Product } from '@/types';

export const FALLBACK_PRODUCTS: Product[] = [
  {
    id: '1',
    created_at: new Date().toISOString(),
    name: 'Premium Kraft Paper Bag',
    slug: 'premium-kraft-paper-bag',
    description: 'High-quality twisted handle kraft paper bag, ideal for retail and gifting.',
    price: null, // Bulk only
    sale_price: null,
    category: 'kraft bags',
    sku: 'KB-001',
    material: '120 GSM Kraft Paper',
    moq: 500,
    is_featured: true,
    is_customizable: true,
    status: 'published',
    images: ['https://picsum.photos/seed/kraft1/800/800'],
    sizes: ['Small (8x10x4")', 'Medium (10x13x5")', 'Large (16x12x6")'],
    colors: ['Natural Brown', 'White'],
    handles: ['Twisted Paper', 'Flat Paper'],
    printing_options: ['Single Color', 'Multi Color Screen Print']
  },
  {
    id: '2',
    created_at: new Date().toISOString(),
    name: 'Luxury Boutique Bag',
    slug: 'luxury-boutique-bag',
    description: 'Elegant laminated paper bag with rope handles for high-end retail.',
    price: 45,
    sale_price: null,
    category: 'designer bags',
    sku: 'DB-002',
    material: '200 GSM Art Paper',
    moq: 200,
    is_featured: true,
    is_customizable: true,
    status: 'published',
    images: ['https://picsum.photos/seed/boutique1/800/800'],
    sizes: ['Small', 'Medium', 'Large'],
    colors: ['Black', 'White', 'Navy', 'Forest Green'],
    handles: ['Cotton Rope', 'Ribbon'],
    printing_options: ['Foil Stamping', 'UV Spot', 'Offset']
  },
  {
    id: '3',
    created_at: new Date().toISOString(),
    name: 'Standard Non-Woven D-Cut',
    slug: 'standard-non-woven-d-cut',
    description: 'Cost-effective, durable reusable bag for everyday retail use.',
    price: 8,
    sale_price: null,
    category: 'non-woven bags',
    sku: 'NW-003',
    material: '60 GSM Non-Woven Fabric',
    moq: 1000,
    is_featured: false,
    is_customizable: true,
    status: 'published',
    images: ['https://picsum.photos/seed/nw1/800/800'],
    sizes: ['10x14"', '12x16"', '14x19"'],
    colors: ['Red', 'Blue', 'Green', 'Yellow', 'Black', 'White'],
    handles: ['D-Cut'],
    printing_options: ['Screen Print']
  },
  {
    id: '4',
    created_at: new Date().toISOString(),
    name: 'Eco-Friendly Grocery W-Cut',
    slug: 'eco-friendly-grocery-w-cut',
    description: 'Sturdy grocery bags with W-cut handles, perfect for supermarkets.',
    price: 12,
    sale_price: null,
    category: 'w-cut bags',
    sku: 'WC-004',
    material: '80 GSM Non-Woven Fabric',
    moq: 2000,
    is_featured: false,
    is_customizable: true,
    status: 'published',
    images: ['https://picsum.photos/seed/wc1/800/800'],
    sizes: ['13x16"', '16x20"'],
    colors: ['White', 'Natural'],
    handles: ['W-Cut'],
    printing_options: ['Flexo Print']
  },
];
