import { Product } from '@/types';

export const FALLBACK_PRODUCTS: Product[] = [
  {
    id: '1',
    created_at: new Date().toISOString(),
    name: 'Eco-Friendly Brown Kraft Paper Bag',
    slug: 'eco-friendly-brown-kraft-paper-bag',
    description: '100% Recyclable virgin brown kraft paper bag with reinforced twisted paper handles and square bottom. Ideal for retail stores, bakeries, cafes, and boutiques.',
    price: 15,
    sale_price: 12,
    category: 'kraft-bags',
    sku: 'MST-KB-001',
    material: '120 GSM Natural Kraft Paper',
    moq: 500,
    is_featured: true,
    is_customizable: true,
    status: 'published',
    images: ['/images/products/kraft-twisted-handle-bags.svg'],
    sizes: ['Small (8x10x4")', 'Medium (10x13x5")', 'Large (16x12x6")'],
    colors: ['Natural Brown', 'Bleached White'],
    handles: ['Twisted Paper', 'Flat Paper'],
    printing_options: ['Single Color Screen Print', 'Multi Color Offset Print', 'Logo Stamping']
  },
  {
    id: '2',
    created_at: new Date().toISOString(),
    name: 'Non-Woven W-Cut Supermarket Bag',
    slug: 'non-woven-w-cut-supermarket-bag',
    description: 'Heavy-duty non-woven W-cut vest handle bag engineered for supermarkets, grocery stores, and department stores. High load bearing capacity.',
    price: 9,
    sale_price: 7.5,
    category: 'w-cut-bags',
    sku: 'MST-WC-002',
    material: '80 GSM Non-Woven Spunbond Fabric',
    moq: 1000,
    is_featured: true,
    is_customizable: true,
    status: 'published',
    images: ['/images/products/wcut-grocery-bags.svg'],
    sizes: ['13x16+4" Gusset', '16x20+5" Gusset', '18x22+6" Gusset'],
    colors: ['Lemon Yellow', 'Off White', 'Navy Blue', 'Bright Red'],
    handles: ['Integrated W-Cut Vest Handle'],
    printing_options: ['Flexographic Print', 'Rotogravure']
  },
  {
    id: '3',
    created_at: new Date().toISOString(),
    name: 'Standard Non-Woven D-Cut Bag',
    slug: 'standard-non-woven-d-cut-bag',
    description: 'Durable and reusable non-woven bag with precision die-cut punch handle. Perfect for apparel shops, footwear, medical stores, and promotional expos.',
    price: 8,
    sale_price: 6.5,
    category: 'd-cut-bags',
    sku: 'MST-NW-003',
    material: '70 GSM Non-Woven Fabric',
    moq: 1000,
    is_featured: true,
    is_customizable: true,
    status: 'published',
    images: ['/images/products/fusion-fashion-bag.svg'],
    sizes: ['10x14 inch', '12x16 inch', '14x19 inch', '16x21 inch'],
    colors: ['Pure White', 'Sunny Yellow', 'Bright Red', 'Maroon', 'Jet Black'],
    handles: ['Die-Cut Punch Handle'],
    printing_options: ['Custom Screen Printing']
  },
  {
    id: '4',
    created_at: new Date().toISOString(),
    name: 'Luxury Rajputi Saafe Boutique Bag',
    slug: 'luxury-rajputi-saafe-boutique-bag',
    description: 'Laminated royal maroon art paper bag with reinforced cardboard top & bottom, braided maroon rope handles, and metallic gold foil logo reproduction.',
    price: 45,
    sale_price: 38,
    category: 'designer-bags',
    sku: 'MST-DB-004',
    material: '210 GSM Art Card with Matte Lamination',
    moq: 300,
    is_featured: true,
    is_customizable: true,
    status: 'published',
    images: ['/images/products/rajputi-saafe-luxury-bag.svg'],
    sizes: ['Small (7x9x3.5")', 'Medium (11x14x4.5")', 'Large (15x18x6")'],
    colors: ['Royal Maroon & Gold', 'Matte Black', 'Pearl White'],
    handles: ['Braided Cotton Rope', 'Silk Satin Ribbon'],
    printing_options: ['Gold Foil Stamping', 'UV Spot', 'Debossing']
  },
  {
    id: '5',
    created_at: new Date().toISOString(),
    name: 'Jalsa Clothing Custom Paper Bag',
    slug: 'jalsa-clothing-custom-paper-bag',
    description: 'Premium white kraft shopping bag with crimson circular brand seal and twisted paper loop handles for fashion apparel and boutiques.',
    price: 24,
    sale_price: 20,
    category: 'paper-bags',
    sku: 'MST-JC-005',
    material: '150 GSM Bleached White Kraft Paper',
    moq: 500,
    is_featured: true,
    is_customizable: true,
    status: 'published',
    images: ['/images/products/jalsa-clothing-bag.svg'],
    sizes: ['8x10x3.5"', '10x13x4"', '14x16x5"'],
    colors: ['Bleached White', 'Crimson Printed'],
    handles: ['Twisted Paper Loop'],
    printing_options: ['Full Color Offset', 'Screen Printing']
  },
  {
    id: '6',
    created_at: new Date().toISOString(),
    name: 'Panchmeva Mahakal Devotional Bag',
    slug: 'panchmeva-mahakal-devotional-bag',
    description: 'White D-Cut non-woven carry bag with red devotional Mahakaleshwar Jyotirlinga imprint and temple prasadi wholesale specifications.',
    price: 7.5,
    sale_price: 6,
    category: 'd-cut-bags',
    sku: 'MST-PM-006',
    material: '70 GSM Spunbond Non-Woven',
    moq: 1000,
    is_featured: true,
    is_customizable: true,
    status: 'published',
    images: ['/images/products/panchmeva-prasadi-bag.svg'],
    sizes: ['10x14 inch', '12x16 inch'],
    colors: ['Pure White with Red Print'],
    handles: ['Die-Cut Punch Handle'],
    printing_options: ['Red Devotional Screen Print']
  },
  {
    id: '7',
    created_at: new Date().toISOString(),
    name: 'Kraft Grocery & Pharmacy Flat Pouches',
    slug: 'kraft-grocery-pharmacy-flat-pouches',
    description: 'Tiered brown kraft flat bottom pouches with serrated top edge for pharmacy medical packaging, bakeries, snacks, and dry fruits.',
    price: 3.5,
    sale_price: 2.8,
    category: 'envelopes',
    sku: 'MST-KP-007',
    material: '60-90 GSM Food Grade Brown Kraft',
    moq: 2000,
    is_featured: false,
    is_customizable: true,
    status: 'published',
    images: ['/images/products/kraft-grocery-pouches.svg'],
    sizes: ['100g', '250g', '500g', '1kg', '2kg', '5kg'],
    colors: ['Natural Brown Kraft'],
    handles: ['Serrated Self-Standing Opening'],
    printing_options: ['Single Color Screen Print', 'Custom Branding']
  },
  {
    id: '8',
    created_at: new Date().toISOString(),
    name: 'Rainbow Multi-Color Loop Handle Bags',
    slug: 'rainbow-multi-color-loop-handle-bags',
    description: 'Vibrant loop handle non-woven carry bags available in 8 attractive colors with reinforced stitched loop handles for retail and exhibitions.',
    price: 11,
    sale_price: 9.5,
    category: 'non-woven-bags',
    sku: 'MST-RB-008',
    material: '80 GSM Virgin Spunbond Fabric',
    moq: 1000,
    is_featured: true,
    is_customizable: true,
    status: 'published',
    images: ['/images/products/rainbow-loop-bags.svg'],
    sizes: ['12x16x4"', '14x18x5"', '16x20x6"'],
    colors: ['Red', 'Yellow', 'Orange', 'Green', 'White', 'Black', 'Cyan', 'Royal Blue'],
    handles: ['Loop Handle'],
    printing_options: ['Screen Printing', 'Flexo']
  }
];

