import { Product } from '@/types';

export const FALLBACK_PRODUCTS: Product[] = [
  {
    id: '1',
    created_at: new Date().toISOString(),
    name: 'Eco-Friendly Brown Kraft Paper Bag',
    slug: 'eco-friendly-brown-kraft-paper-bag',
    description: '100% Recyclable virgin brown kraft paper bag with reinforced twisted paper handles and square bottom. Ideal for retail stores, bakeries, cafes, and boutiques.',
    price: 15,
    sale_price: 12,
    category: 'kraft-bags',
    sku: 'MST-KB-001',
    material: '120 GSM Natural Kraft Paper',
    moq: 500,
    is_featured: true,
    is_customizable: true,
    status: 'published',
    images: ['https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=800&q=80'],
    sizes: ['Small (8x10x4")', 'Medium (10x13x5")', 'Large (16x12x6")'],
    colors: ['Natural Brown', 'Bleached White'],
    handles: ['Twisted Paper', 'Flat Paper'],
    printing_options: ['Single Color Screen Print', 'Multi Color Offset Print', 'Logo Stamping']
  },
  {
    id: '2',
    created_at: new Date().toISOString(),
    name: 'Non-Woven W-Cut Supermarket Bag',
    slug: 'non-woven-w-cut-supermarket-bag',
    description: 'Heavy-duty non-woven W-cut vest handle bag engineered for supermarkets, grocery stores, and department stores. High load bearing capacity.',
    price: 9,
    sale_price: 7.5,
    category: 'w-cut-bags',
    sku: 'MST-WC-002',
    material: '80 GSM Non-Woven Spunbond Fabric',
    moq: 1000,
    is_featured: true,
    is_customizable: true,
    status: 'published',
    images: ['https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?auto=format&fit=crop&w=800&q=80'],
    sizes: ['13x16+4" Gusset', '16x20+5" Gusset', '18x22+6" Gusset'],
    colors: ['Navy Blue', 'Forest Green', 'Bright Red', 'Off White', 'Yellow'],
    handles: ['Integrated W-Cut Vest Handle'],
    printing_options: ['Flexographic Print', 'Rotogravure']
  },
  {
    id: '3',
    created_at: new Date().toISOString(),
    name: 'Standard Non-Woven D-Cut Bag',
    slug: 'standard-non-woven-d-cut-bag',
    description: 'Durable and reusable non-woven bag with precision die-cut punch handle. Perfect for apparel shops, footwear, medical stores, and promotional expos.',
    price: 8,
    sale_price: 6.5,
    category: 'd-cut-bags',
    sku: 'MST-NW-003',
    material: '70 GSM Non-Woven Fabric',
    moq: 1000,
    is_featured: true,
    is_customizable: true,
    status: 'published',
    images: ['https://images.unsplash.com/photo-1597484661643-2f5fef640dd1?auto=format&fit=crop&w=800&q=80'],
    sizes: ['10x14 inch', '12x16 inch', '14x19 inch', '16x21 inch'],
    colors: ['Maroon', 'Teal', 'Royal Blue', 'Jet Black', 'Pure White'],
    handles: ['Die-Cut Punch Handle'],
    printing_options: ['Custom Screen Printing']
  },
  {
    id: '4',
    created_at: new Date().toISOString(),
    name: 'Luxury Boutique Designer Paper Bag',
    slug: 'luxury-boutique-designer-paper-bag',
    description: 'Laminated imported art paper bag with reinforced cardboard top & bottom, braided cotton rope handles, and metallic gold foil logo reproduction.',
    price: 45,
    sale_price: 38,
    category: 'designer-bags',
    sku: 'MST-DB-004',
    material: '210 GSM Art Card with Matte Lamination',
    moq: 300,
    is_featured: true,
    is_customizable: true,
    status: 'published',
    images: ['https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=800&q=80'],
    sizes: ['Small (7x9x3.5")', 'Medium (11x14x4.5")', 'Large (15x18x6")'],
    colors: ['Matte Black', 'Pearl White', 'Deep Navy', 'Burgundy'],
    handles: ['Braided Cotton Rope', 'Silk Satin Ribbon'],
    printing_options: ['Gold Foil Stamping', 'UV Spot', 'Debossing']
  },
  {
    id: '5',
    created_at: new Date().toISOString(),
    name: 'Festive Wedding & Celebration Gift Bag',
    slug: 'festive-wedding-celebration-gift-bag',
    description: 'Vibrant patterned paper gift bag designed for Indian weddings, festivals, corporate Diwali return gifts, and sweets packaging.',
    price: 32,
    sale_price: 28,
    category: 'gift-bags',
    sku: 'MST-GB-005',
    material: '180 GSM Glossy Coated Board',
    moq: 250,
    is_featured: true,
    is_customizable: true,
    status: 'published',
    images: ['https://images.unsplash.com/photo-1513885535751-8b9238bd345a?auto=format&fit=crop&w=800&q=80'],
    sizes: ['8x10x3.5"', '10x12x4"', '12x15x5"'],
    colors: ['Crimson Red & Gold', 'Emerald & Gold', 'Royal Purple'],
    handles: ['Golden Twisted Cord', 'Satin Ribbon'],
    printing_options: ['Full Color Print with Gold Foil Accents']
  },
  {
    id: '6',
    created_at: new Date().toISOString(),
    name: 'Custom Printed Polythene Carry Bag',
    slug: 'custom-printed-polythene-carry-bag',
    description: 'High-density custom printed plastic carry bag with loop handle or punch handle options for wholesale, hardware, and retail store packaging.',
    price: 7,
    sale_price: 5.5,
    category: 'customized-bags',
    sku: 'MST-PB-006',
    material: '50+ Micron Recyclable Polyethylene',
    moq: 2000,
    is_featured: false,
    is_customizable: true,
    status: 'published',
    images: ['https://images.unsplash.com/photo-1572021335469-31706a17aaef?auto=format&fit=crop&w=800&q=80'],
    sizes: ['11x14"', '13x17"', '16x20"'],
    colors: ['Milky White', 'Clear Transparent', 'Silver Grey'],
    handles: ['Soft Loop Handle', 'Punch Cut Handle'],
    printing_options: ['Multi-Color Flexo Printing']
  }
];

